// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElSlider: typeof import('element-plus/es')['ElSlider']
}
export {}
